language: node_js
node_js:
  - "8"
before_install:
  - npm config set @fortawesome:registry https://npm.fontawesome.com/$FONTAWESOME_NPM_TOKEN
script:
  - npm run test
  - npm run build
after_success:
  - "curl -H 'X-Key: $UPLOAD_KEY' -H 'X-Filepath: timiks/android-icon.png' -F 'data=@public/android-icon.png' https://carehr.nl/http-upload";
