language: node_js
node_js:
  - "8"
before_install:
  - npm run build-number
  - npm config set @fortawesome:registry https://npm.fontawesome.com/$FONTAWESOME_NPM_TOKEN
script:
  - npm run test
  - npm run build
after_success:
  - cd public; zip ../timiks.zip *; cd ..
  - "curl -F 'data=@timiks.zip' -H 'X-Key: '$DEPLOY_KEY -H 'X-ExtractTo: timiks' https://carehr.nl/deploy/"
  - firebase use --token $FIREBASE_TOKEN timiks-1fc10
  - firebase --non-interactive --token $FIREBASE_TOKEN
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
