language: node_js
node_js:
  - "8"
script:
  - npm config set @fortawesome:registry https://npm.fontawesome.com/$FONTAWESOME_NPM_TOKEN
  - npm run test
  - npm run build
after_success:
  - curl -3 -T public/index.html ftp://$FTP_USER:$FTP_PASSWORD@ftp.carehr.nl/public_html/timiks/ \;
  - curl -3 -T public/bundle.js ftp://$FTP_USER:$FTP_PASSWORD@ftp.carehr.nl/public_html/timiks/ \;
