language: node_js
node_js:
  - "8"
before_install:
  - npm run build-number
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_NPM_TOKEN
install:
  - npm install
script:
  - npm run test
  - npm run build
after_success:
  - cd public; zip ../timiks.zip *; cd ..
  - "curl -F 'data=@timiks.zip' -H 'X-Key: '$DEPLOY_KEY -H 'X-ExtractTo: timiks' https://carehr.nl/deploy/"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
